### ISSUE TITLE
Build a system to encourage users to invite new users 

### ISSUE THREAD

**Issue by johan-t** [Contraversum/ContraBot#15]
We need to encourage the spreading of the server over word of mouth 

Ideas:

- user invitation score
- role for how long you have been on the sever

**Comment by TheLlamamarketer** [comment]
>How do I set up invite roles?            (aka rewarding people for inviting more users)
 >This feature has sadly been disabled due to it being against Discord's Developer Terms of Service. Having any features that include rewarding invites just enables server advertisement in servers and direct messages. This is something Discord views as unsolicited advertisement, which is exactly what breaks the Discord Developer Policy.

**Comment by johan-t** [comment]
But it works for us, we give users roles after the test

**Comment by johan-t** [comment]
@TheLlamamarketer What we could do for now is that we just have a role: 'first 50', 'first 100' etc you could write a loop that has certain breakpoints and for every new user it gives them the role according to their breakpoint. This would maybe be a first step to get the ball going
